#!/bin/bash
clear
start=$(date +%s)
# Colors for output
C='\e[1;32m'
G='\e[1;32m'
N='\e[0m'
W='\e[1;37m'

# REPOSITORY
REPOKU="https://raw.githubusercontent.com/genome96/lastone/main"
REPOSC="https://raw.githubusercontent.com/genome96/lastone/main"
REPOKEY="https://raw.githubusercontent.com/genome96/lastone/main"

# TELEGRAM
CHATID="7350152532"
TOKENBOT="7196846248:AAH0HElyt7EGmAf8wJuF3CmJrHaU49sAy7Q"

# Check if running as root
cd /root
if [ "${EUID}" -ne 0 ]; then
    echo "You need to run this script as root"
    exit 1
fi

if [ "$(systemd-detect-virt)" == "openvz" ]; then
    echo "OpenVZ is not supported"
    exit 1
fi

localip=$(hostname -I | cut -d\  -f1)
hst=( `hostname` )
dart=$(cat /etc/hosts | grep -w `hostname` | awk '{print $2}')
if [[ "$hst" != "$dart" ]]; then
    echo "$localip $(hostname)" >> /etc/hosts
fi

function STARTING() {
    echo -e "  Installation time: ${C} $(( ${1} / 3600 )) ${N} hours${C} $(( (${1} / 60) % 60 )) ${N} minutes${C} $(( ${1} % 60 )) ${N} seconds"
}
rm -rf /etc/alawivpn
mkdir -p /etc/alawivpn
mkdir -p /etc/alawivpn/theme
mkdir -p /var/lib/ >/dev/null 2>&1
echo "IP=" >> /var/lib/ipvps.conf
clear
echo
echo -e " ${C}╔══════════════════════════════════════════╗${N}"
echo -e " ${C}║${W}            ENTER YOUR NAME               ${C}║${N}"
echo -e " ${C}╚══════════════════════════════════════════╝${N}"
echo " "
until [[ $name =~ ^[a-zA-Z0-9_.-]+$ ]]; do
    read -rp "  Enter your name without spaces: " -e name
done
rm -rf /etc/profil
echo "$name" > /etc/profil
author=$(cat /etc/profil | awk '{print $1}')

function isi_github_info(){
    echo -e "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" > /etc/github/api
    echo -e "optimusglitch@gmail.com" > /etc/github/email
    echo -e "genome96" > /etc/github/username
}

function isikey(){
    clear
    echo
    echo -e "${C}╔══════════════════════════════════════════╗${N}"
    echo -e "${C}║${W}         ACTIVATION MENU OPTIONS           ${C}║${N}"
    echo -e "${C}╚══════════════════════════════════════════╝${N}"
    echo -e "${C}╔══════════════════════════════════════════╗${N}"
    echo -e "${C}║                                          ║${N}"
    echo -e "${C}║${W}  [${C}01${W}] TRIAL 1 DAY                         ${C}║${N}"
    echo -e "${C}║                                          ║${N}"
    echo -e "${C}║${W}  [${C}02${W}] MEMBER PURCHASED                    ${C}║${N}"
    echo -e "${C}║                                          ║${N}"
    echo -e "${C}╚══════════════════════════════════════════╝${N}"
    until [[ $key =~ ^[12]+$ ]]; do
        read -p "  Please select 1 or 2: " key
    done
    if [[ $key == "1" ]]; then
        MYIP=$(curl -sS ipv4.icanhazip.com)
        rm -rf /etc/github
        mkdir -p /etc/github
        isi_github_info
        clear
        APIGIT=$(cat /etc/github/api)
        EMAILGIT=$(cat /etc/github/email)
        USERGIT=$(cat /etc/github/username)
        hhari=$(date -d "1 days" +"%Y-%m-%d")
        mkdir -p /root/alawi
        cd /root/alawi
        wget ${REPOKU}/registrasi.txt >/dev/null 2>&1
        echo "### $author $hhari $MYIP @trial" >> registrasi.txt
        sleep 1
        rm -rf .git
        git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
        git config --global user.name "${USERGIT}" >/dev/null 2>&1
        git init >/dev/null 2>&1
        git add registrasi.txt
        git commit -m register >/dev/null 2>&1
        git branch -M script >/dev/null 2>&1
        git remote add origin https://github.com/${USERGIT}/lastone >/dev/null 2>&1
        git push -f https://${APIGIT}@github.com/${USERGIT}/lastone >/dev/null 2>&1
        sleep 1
        rm -rf /root/alawi
        rm -rf /etc/github
        clear
    fi
    if [[ $key == "2" ]]; then
        clear
        echo
        echo -e  "${C}╔══════════════════════════════════════════╗${N}"
        echo -e  "${C}║${W}          ENTER LICENSE KEY              ${C}║${N}"
        echo -e  "${C}╚══════════════════════════════════════════╝${N}"
        echo " "
        read -rp " Enter your key here (Ctrl + C to Exit): " -e kode

        if [ -z $kode ]; then
            echo -e " INVALID CODE, PLEASE ENTER AGAIN"
            key2
        fi
        LIST=$(curl -sS ${REPOKEY}/key | grep $kode | awk '{print $2}')
        Key=$(curl -sS ${REPOKEY}/key | grep $kode | awk '{print $3}')
        KEY2=$(curl -sS ${REPOKEY}/key | grep $kode | awk '{print $4}')
        ADMIN=$(curl -sS ${REPOKEY}/key | grep $kode | awk '{print $5}')
        TOTALIP=$(curl -sS ${REPOKEY}/key | grep $kode | awk '{print $6}')
        cd
        if [[ $kode == "BISMILLAH" ]]; then
            MYIP=$(curl -sS ipv4.icanhazip.com)
            rm -rf /etc/github
            mkdir -p /etc/github
            isi_github_info
            clear
            APIGIT=$(cat /etc/github/api)
            EMAILGIT=$(cat /etc/github/email)
            USERGIT=$(cat /etc/github/username)
            hhari=$(date -d "30 days" +"%Y-%m-%d")
            mkdir -p /root/alawi
            cd /root/alawi
            wget ${REPOKU}/registrasi.txt >/dev/null 2>&1

            echo "### $author $hhari $MYIP @itgizmo" >> registrasi.txt

            sleep 0.5
            rm -rf .git
            git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
            git config --global user.name "${USERGIT}" >/dev/null 2>&1
            git init >/dev/null 2>&1
            git add registrasi.txt
            git commit -m register >/dev/null 2>&1
            git branch -M script >/dev/null 2>&1
            git remote add origin https://github.com/${USERGIT}/lastone >/dev/null 2>&1
            git push -f https://${APIGIT}@github.com/${USERGIT}/lastone >/dev/null 2>&1
            sleep 0.5
            rm registrasi.txt
        elif [[ $kode == "SUBHANALLAH" ]]; then
            MYIP2=$(curl -sS ipv4.icanhazip.com)
            rm -rf /etc/github
            mkdir -p /etc/github
            isi_github_info
            clear
            APIGIT=$(cat /etc/github/api)
            EMAILGIT=$(cat /etc/github/email)
            USERGIT=$(cat /etc/github/username)
            hhari2=$(date -d "999 days" +"%Y-%m-%d")
            mkdir -p /root/alawi
            cd /root/alawi
            wget ${REPOKU}/registrasi.txt >/dev/null 2>&1

            sed -i "/# VIP/a ### ${author} ${hhari2} ${MYIP2} ON 999 VIP" /root/alawi/registrasi.txt

            sleep 0.5
            rm -rf .git
            git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
            git config --global user.name "${USERGIT}" >/dev/null 2>&1
            git init >/dev/null 2>&1
            git add registrasi.txt
            git commit -m register >/dev/null 2>&1
            git branch -M script >/dev/null 2>&1
            git remote add origin https://github.com/${USERGIT}/lastone >/dev/null 2>&1
            git push -f https://${APIGIT}@github.com/${USERGIT}/lastone >/dev/null 2>&1
            sleep 0.5
            rm registrasi.txt
        elif [[ $kode == "ALHAMDULILLAH" ]]; then
            MYIP3=$(curl -sS ipv4.icanhazip.com)
            rm -rf /etc/github
            mkdir -p /etc/github
            isi_github_info
            clear
            APIGIT=$(cat /etc/github/api)
            EMAILGIT=$(cat /etc/github/email)
            USERGIT=$(cat /etc/github/username)
            hhari3=$(date -d "999 days" +"%Y-%m-%d")
            mkdir -p /root/alawi
            cd /root/alawi
            wget ${REPOKU}/registrasi.txt >/dev/null 2>&1

            sed -i "/# RESELLER/a ### ${author} ${hhari3} ${MYIP3} ON 999" /root/alawi/registrasi.txt

            sleep 0.5
            rm -rf .git
            git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
            git config --global user.name "${USERGIT}" >/dev/null 2>&1
            git init >/dev/null 2>&1
            git add registrasi.txt
            git commit -m register >/dev/null 2>&1
            git branch -M script >/dev/null 2>&1
            git remote add origin https://github.com/${USERGIT}/lastone >/dev/null 2>&1
            git push -f https://${APIGIT}@github.com/${USERGIT}/lastone >/dev/null 2>&1
            sleep 0.5
            rm registrasi.txt
        elif [[ $kode == $Key ]]; then
            MYIP=$(curl -sS ipv4.icanhazip.com)
            rm -rf /etc/github
            mkdir -p /etc/github
            isi_github_info
            clear
            APIGIT=$(cat /etc/github/api)
            EMAILGIT=$(cat /etc/github/email)
            USERGIT=$(cat /etc/github/username)
            hhari=$(date -d "$KEY2 days" +"%Y-%m-%d")
            mkdir -p /root/alawi
            cd /root/alawi
            wget ${REPOKU}/registrasi.txt >/dev/null 2>&1
            if [ "$ADMIN" = "ON" ]; then
                sed -i "/# RESELLER/a ### ${author} ${hhari} ${MYIP} ${ADMIN} ${TOTALIP}" /root/alawi/registrasi.txt
            else
                echo "### $author $hhari $MYIP @$LIST" >> registrasi.txt
            fi

            sleep 0.5
            rm -rf .git
            git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
            git config --global user.name "${USERGIT}" >/dev/null 2>&1
            git init >/dev/null 2>&1
            git add registrasi.txt
            git commit -m register >/dev/null 2>&1
            git branch -M script >/dev/null 2>&1
            git remote add origin https://github.com/${USERGIT}/lastone >/dev/null 2>&1
            git push -f https://${APIGIT}@github.com/${USERGIT}/lastone >/dev/null 2>&1
            sleep 0.5
            rm registrasi.txt
            wget ${REPOKEY}/key >/dev/null 2>&1
            if [ "$ADMIN" = "ON" ]; then
                sed -i "/^### $LIST $Key $KEY2 $ADMIN $TOTALIP/d" /root/alawi/key
            else
                sed -i "/^### $LIST $Key $KEY2/d" /root/alawi/key
            fi
            sleep 0.5
            rm -rf .git
            git config --global user.email "${EMAILGIT}" >/dev/null 2>&1
            git config --global user.name "${USERGIT}" >/dev/null 2>&1
            git init >/dev/null 2>&1
            git add key
            git commit -m register >/dev/null 2>&1
            git branch -M script >/dev/null 2>&1
            git remote add origin https://github.com/${USERGIT}/license >/dev/null 2>&1
            git push -f https://${APIGIT}@github.com/${USERGIT}/license >/dev/null 2>&1
            rm -rf /root/alawi
            rm -rf /etc/github
            clear
        else
            echo -e " INVALID CODE, PLEASE ENTER AGAIN"
            sleep 1
            key2
        fi
    fi
}

function domain(){
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;33m  Updating Domain... \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m●"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;33m  Updating Domain... \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m Success!\033[1;37m"
    tput cnorm
}
res1() {
    wget -q ${REPOSC}/install/pointing.sh && chmod +x pointing.sh && ./pointing.sh
    clear
}
cd
clear
echo
echo -e " ${C}╔══════════════════════════════════════════╗${N}"
echo -e " ${C}║${W}     DOMAIN INPUT MENU FOR VPS           ${C}║${N}"
echo -e " ${C}╚══════════════════════════════════════════╝${N}"
echo -e " ${C}╔══════════════════════════════════════════╗${N}"
echo -e " ${C}║${W} [${C}01${W}] Your own domain                    ${C}║${N}"
echo -e " ${C}║                                          ║${N}"
echo -e " ${C}║${W} [${C}02${W}] Script-owned domain                ${C}║${N}"
echo -e " ${C}║                                          ║${N}"
echo -e " ${C}║${W} [${C}03${W}] Your own Host & SlowDNS domain     ${C}║${N}"
echo -e " ${C}╚══════════════════════════════════════════╝${N}"
until [[ $domain =~ ^[132]+$ ]]; do
    read -p "  Enter your choice 1/2/3: " domain
done
if [[ $domain == "1" ]]; then
    until [[ $dnss =~ ^[a-zA-Z0-9_.-]+$ ]]; do
        echo
        read -rp "  Enter your domain here: " -e dnss
    done
    rm -rf /etc/xray
    rm -rf /etc/v2ray
    rm -rf /etc/nsdomain
    rm -rf /etc/per
    mkdir -p /etc/xray
    mkdir -p /etc/v2ray
    mkdir -p /etc/nsdomain
    touch /etc/xray/domain
    touch /etc/v2ray/domain
    touch /etc/xray/slwdomain
    touch /etc/v2ray/scdomain
    echo "$dnss" > /root/domain
    echo "$dnss" > /root/scdomain
    echo "$dnss" > /etc/xray/scdomain
    echo "$dnss" > /etc/v2ray/scdomain
    echo "$dnss" > /etc/xray/domain
    echo "$dnss" > /etc/v2ray/domain
    echo "IP=$dnss" > /var/lib/ipvps.conf
    echo ""
    clear
fi
if [[ $domain == "2" ]]; then
    clear
    echo
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}     SCRIPT-OWNED DOMAIN MENU             ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W} [${C}01${W}] Domain xxx.alawivpn.cloud           ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    until [[ $domain2 =~ ^[1]+$ ]]; do
        read -p "  Enter your choice number 1: " domain2
    done
fi
if [[ $domain2 == "1" ]]; then
    until [[ $dn1 =~ ^[a-zA-Z0-9_.-]+$ ]]; do
        echo
        read -rp "  Enter your subdomain here without spaces: " -e dn1
    done
    rm -rf /etc/xray
    rm -rf /etc/v2ray
    rm -rf /etc/nsdomain
    rm -rf /etc/per
    mkdir -p /etc/xray
    mkdir -p /etc/v2ray
    mkdir -p /etc/nsdomain
    mkdir -p /etc/per
    touch /etc/per/id
    touch /etc/per/token
    touch /etc/xray/domain
    touch /etc/v2ray/domain
    touch /etc/xray/slwdomain
    touch /etc/v2ray/scdomain
    echo "$dn1" > /root/subdomainx
    cd
    sleep 1
    clear
    echo
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}   POINTING DOMAIN TO CLOUDFLARE           ${C}║"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res1'
    clear
    rm /root/subdomainx
fi

if [[ $domain == "3" ]]; then
    until [[ $dns1 =~ ^[a-zA-Z0-9_.-]+$ ]]; do
        read -rp "  Enter your domain here: " -e dns1
    done
    echo ""
    echo "$dns1" > /etc/xray/domain
    echo "$dns1" > /etc/v2ray/domain
    echo "IP=$dns1" > /var/lib/ipvps.conf
    until [[ $dns2 =~ ^[a-zA-Z0-9_.-]+$ ]]; do
        read -rp "  Enter your SlowDNS domain here: " -e dns2
    done
    echo $dns2 >/etc/xray/dns
fi
}
cat <<EOF>> /etc/alawivpn/theme/green
BG : \e[37;1;42m
TEXT : \033[0;32m
EOF
cat <<EOF>> /etc/alawivpn/theme/yellow
BG : \e[37;1;43m
TEXT : \033[0;33m
EOF
cat <<EOF>> /etc/alawivpn/theme/red
BG : \e[37;1;41m
TEXT : \033[0;31m
EOF
cat <<EOF>> /etc/alawivpn/theme/blue
BG : \e[37;1;44m
TEXT : \033[0;34m
EOF
cat <<EOF>> /etc/alawivpn/theme/magenta
BG : \e[37;1;45m
TEXT : \033[0;35m
EOF
cat <<EOF>> /etc/alawivpn/theme/cyan
BG : \e[37;1;46m
TEXT : \033[0;36m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightgray
BG : \e[37;1;47m
TEXT : \033[0;37m
EOF
cat <<EOF>> /etc/alawivpn/theme/darkgray
BG : \e[37;1;100m
TEXT : \033[0;90m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightred
BG : \e[37;1;101m
TEXT : \033[0;91m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightgreen
BG : \e[37;1;102m
TEXT : \033[0;92m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightyellow
BG : \e[37;1;103m
TEXT : \033[0;93m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightblue
BG : \e[37;1;104m
TEXT : \033[0;94m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightmagenta
BG : \e[37;1;105m
TEXT : \033[0;95m
EOF
cat <<EOF>> /etc/alawivpn/theme/lightcyan
BG : \e[37;1;106m
TEXT : \033[0;96m
EOF
cat <<EOF>> /etc/alawivpn/theme/color.conf
lightgreen
EOF
function ALAWIVPN(){
    cd
    sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
    sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null 2>&1
    clear
    wget -q ${REPOSC}/tools.sh &> /dev/null
    chmod +x tools.sh
    ./tools.sh
    clear
    ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    apt install git curl -y >/dev/null 2>&1
    apt install python -y >/dev/null 2>&1
}

function CEKIP () {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IPVPS=$(curl -sS $REPOKU/registrasi.txt | grep $MYIP | awk '{print $4}')
    if [[ $MYIP == $IPVPS ]]; then
        domain
        ALAWIVPN
    else
        cd
        echo " You are not allowed"
        rm -rf /* > /dev/null 2>&1 &
        exit
    fi
}

function ALAWIVPNANIMASI(){
    fun_bar() {
        CMD[0]="$1"
        CMD[1]="$2"
        (
            [[ -e $HOME/fim ]] && rm $HOME/fim
            ${CMD[0]} -y >/dev/null 2>&1
            ${CMD[1]} -y >/dev/null 2>&1
            touch $HOME/fim
        ) >/dev/null 2>&1 &
        tput civis
        echo -ne "\033[1;33m  Installing Files \033[1;37m- \033[1;33m["
        while true; do
            for ((i = 0; i < 16; i++)); do
                echo -ne "\033[0;32m●"
                sleep 0.1s
            done
            [[ -e $HOME/fim ]] && rm $HOME/fim && break
            echo -e "\033[0;33m]"
            sleep 1s
            tput cuu1
            tput dl1
            echo -ne "\033[1;33m  Installing Files \033[1;37m- \033[1;33m["
        done
        echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK!\033[1;37m"
        tput cnorm
    }


    res2() {
        wget -q ${REPOSC}/install/ssh-vpn.sh && chmod +x ssh-vpn.sh && ./ssh-vpn.sh
        clear
    }

    res3() {
        wget -q ${REPOSC}/install/ins-xray.sh && chmod +x ins-xray.sh && ./ins-xray.sh
        clear
    }

    res4() {
        wget -q ${REPOSC}/sshws/insshws.sh && chmod +x insshws.sh && ./insshws.sh
        clear
    }

    res5() {
        wget -q ${REPOSC}/install/set-br.sh && chmod +x set-br.sh && ./set-br.sh
        clear
    }

    res6() {
        wget -q ${REPOSC}/sshws/ohp.sh && chmod +x ohp.sh && ./ohp.sh
        clear
    }

    res7() {
        wget -q ${REPOSC}/menu/ekstra.sh && chmod +x ekstra.sh && ./ekstra.sh
        clear
    }

    res8() {
        # wget -q ${REPOSC}/slowdns/installsl.sh && chmod +x installsl.sh && ./installsl.sh
        echo " Not used"
        clear
    }

    res9() {
        wget -q ${REPOSC}/install/udp-custom.sh && chmod +x udp-custom.sh && ./udp-custom.sh
        clear
    }

    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}       INSTALLING SSH & OVPN              ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res2'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}          INSTALLING XRAY                 ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res3'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}      INSTALLING SSH WEBSOCKET            ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res4'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}       INSTALLING BACKUP MENU             ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res5'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}           INSTALLING OHP                 ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res6'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}       INSTALLING EXTRA MENU              ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res7'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}       INSTALLING UDP CUSTOM              ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    fun_bar 'res9'
    echo -e " ${C}╔══════════════════════════════════════════╗${N}"
    echo -e " ${C}║${W}          SCRIPT INSTALLATION TIME        ${C}║${N}"
    echo -e " ${C}╚══════════════════════════════════════════╝${N}"
    STARTING "$(($(date +%s) - ${start}))" | tee -a log-install.txt
}

function convert() {
    local -i megabytes=$1
    if [[ $megabytes -lt 1024 ]]; then
        echo "${megabytes} MB"
    else
        echo "$(awk "BEGIN {printf \"%.1f\", $megabytes/1024}" | sed 's/\.0$//') GB"
    fi
}

function conv() { date -u -d "@$1" +'%H:%M:%S'; }

function TERAKHIR(){
    finish=$(date +%s)
    instalasi=$((finish - start))
    TIMES="10"
    CHATID="$CHATID"
    KEY="$TOKENBOT"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10)
    CITY=$(curl -s ipinfo.io/city)
    domain=$(cat /etc/xray/domain)
    TIME=$(date +'%d-%m-%Y | %H:%M %Z')
    RAM=$(free -m | awk 'NR==2 {print $2}'); RAM=$(convert $RAM)
    MODEL2=$(grep -w PRETTY_NAME /etc/os-release | awk -F'=' '{print $2}' | sed 's/"//g' | sed 's/ *(.*)//' | awk '{for(i=1;i<=10;i++) printf $i" "; if(NF>10) printf "..."; print ""}')
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS ${REPOKU}/registrasi.txt | grep $MYIP | awk '{print $3}' )
    d1=$(date -d "$IZIN" +%s)
    d2=$(date -d "$today" +%s)
    EXP=$(( (d1 - d2) / 86400 ))
    proses=$(conv $instalasi)
    TEXT="<code>
━━━━━━━━━━━━━━━━━━━━━━━━━━
  ☘️ AUTOSCRIPT INSTALLED ☘️
━━━━━━━━━━━━━━━━━━━━━━━━━━
☘️ USER : ${author}
☘️ IP   : ${MYIP}
☘️ HOST : ${domain}
☘️ ISP  : ${ISP}
☘️ CITY : ${CITY}
☘️ OS   : ${MODEL2}
☘️ RAM  : ${RAM}
☘️ TIME : $proses
☘️ EXP  : ${IZIN} (${EXP} Days)
━━━━━━━━━━━━━━━━━━━━━━━━━━
    ${TIME}
━━━━━━━━━━━━━━━━━━━━━━━━━━
</code>"'&reply_markup={"inline_keyboard":[[{"text":"☘️ ORDER","url":"https://t.me/alawivpn"},{"text":"GROUP ☘️","url":"https://t.me/configsantri"}]]}'
    curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function FINISHING() {
    cat> /root/.profile << END
if [ "$BASH" ]; then
    if [ -f ~/.bashrc ]; then
        . ~/.bashrc
    fi
fi
mesg n || true
clear
menu2
END
    echo -e "alias x='exit'\n" >> ~/.bashrc
    chmod 644 /root/.profile
    if [ -f "/root/log-install.txt" ]; then
        rm /root/log-install.txt > /dev/null 2>&1
    fi
    if [ -f "/etc/afak.conf" ]; then
        rm /etc/afak.conf > /dev/null 2>&1
    fi
    if [ ! -f "/etc/log-create-user.log" ]; then
        echo "Log All Account " > /etc/log-create-user.log
    fi
    history -c
    serverV=$( curl -sS ${REPOSC}/versi  )
    echo $serverV > /opt/.ver
    aureb=$(cat /home/re_otm)
    b=11
    if [ $aureb -gt $b ]; then
        gg="PM"
    else
        gg="AM"
    fi
    cd
    curl -sS ipv4.icanhazip.com > /etc/myipvps
    curl -s ipinfo.io/city?token=75082b4831f909 >> /etc/xray/city
    curl -s ipinfo.io/org?token=75082b4831f909  | cut -d " " -f 2-10 >> /etc/xray/isp
    rm /root/setup.sh >/dev/null 2>&1
    rm /root/slhost.sh >/dev/null 2>&1
    rm /root/ssh-vpn.sh >/dev/null 2>&1
    rm /root/ins-xray.sh >/dev/null 2>&1
    rm /root/insshws.sh >/dev/null 2>&1
    rm /root/set-br.sh >/dev/null 2>&1
    rm /root/ohp.sh >/dev/null 2>&1
    rm /root/ekstra.sh >/dev/null 2>&1
    rm /root/slowdns.sh >/dev/null 2>&1
}

CEKIP
ALAWIVPNANIMASI
TERAKHIR
FINISHING
cd
rm -rf *
echo -e " ${C}╔══════════════════════════════════════════╗${N}"
echo -e " ${C}║${W}      VPS WILL REBOOT IN 5 SECONDS        ${C}║${N}"
echo -e " ${C}╚══════════════════════════════════════════╝${N}"
tput civis
for i in {5..1}
do
    echo -ne "\r  Rebooting in ${G}$i${N} seconds.."
    sleep 1
done
echo -ne "\r  Rebooting now..!!    \n"
tput cnorm
clear
reboot