#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
REPOKU="https://www.vmessh.cloud"
REPOSC="https://iam.scvpn.cloud"

biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
COLOR1="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'
U=$COLOR1
O=$COLBG1
W=$WH
N=$NC
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ "$date_list" > "$useexp" ]]; then
        systemctl stop nginx
        systemctl stop kyt
        systemctl stop xray
        systemctl stop ws-stunnel
        dilarang
        exit 1
    else
        echo -ne
    fi
}
checking_sc
IP=$(curl -sS ipv4.icanhazip.com);
date=$(date +"%d-%m-%Y")
time=$(date +"%H:%M:%S %Z")
domain=$(cat /etc/xray/domain)
token=$(cat /usr/bin/token)
id_chat=$(cat /usr/bin/idchat)
clear
sleep 1
echo -e "
 $U——————————————————————————————————————————————$N
 $O        MEMBACKUP DATA VPS KE TELEGRAM        $N
 $U——————————————————————————————————————————————$N
"
echo -e " [${U} INFO ${W}] Processing... "
mkdir -p /root/backup
echo -e " [${U} INFO ${W}] Mohon Ditunggu... "
cp -r /etc/passwd /root/backup/ &> /dev/null
cp -r /etc/group /root/backup/ &> /dev/null
cp -r /etc/shadow /root/backup/ &> /dev/null
cp -r /etc/gshadow /root/backup/ &> /dev/null
cp -r /usr/bin/idchat /root/backup/ &> /dev/null
cp -r /usr/bin/token /root/backup/ &> /dev/null
cp -r /etc/per/id /root/backup/ &> /dev/null
cp -r /etc/per/token /root/backup/token2 &> /dev/null
cp -r /etc/perlogin/id /root/backup/loginid &> /dev/null
cp -r /etc/perlogin/token /root/backup/logintoken &> /dev/null
cp -r /etc/botexp/id /root/backup/expid &> /dev/null
cp -r /etc/botexp/token /root/backup/exptoken &> /dev/null
cp -r /etc/xray/config.json /root/backup/xray &> /dev/null
cp -r /etc/xray/ssh /root/backup/ssh &> /dev/null
cp -r /etc/xray/domain /root/backup/domain &> /dev/null
cp -r /home/vps/public_html /root/backup/public_html &> /dev/null
cp -r /etc/xray/sshx /root/backup/sshx &> /dev/null
cp -r /etc/vmess /root/backup/vmess &> /dev/null
cp -r /etc/vless /root/backup/vless &> /dev/null
cp -r /etc/trojan /root/backup/trojan &> /dev/null
cp -r /etc/issue.net /root/backup/issue &> /dev/null
cd /root
zip -r $IP.zip backup > /dev/null 2>&1
curl -F chat_id="$id_chat" -F document=@"$IP.zip" -F caption="
━━━━━━━━━━━━━━━━━━━━
  <b>☘ VPS SERVER BACKUP ☘</b>
━━━━━━━━━━━━━━━━━━━━
<b>» IP : </b>  <code>$IP</code>
<b>» Host : </b>  <code>$domain</code>
<b>» Date : </b>  <code>$date</code>
<b>» Time : </b>  <code>$time</code>
━━━━━━━━━━━━━━━━━━━━
<b>» @alawivpn</b>
━━━━━━━━━━━━━━━━━━━━
" -F parse_mode=HTML https://api.telegram.org/bot$token/sendDocument &> /dev/null
rm -fr /root/backup &> /dev/null
rm -fr /root/user-backup &> /dev/null
rm -f /root/$NameUser.zip &> /dev/null
rm -r /root/$IP-$date.zip &> /dev/null
rm -f /root/$IP.zip &> /dev/null
echo -e " [${U} INFO ${W}] Silahkan cek botnya!"
echo -e "
 $U——————————————————————————————————————————————$N
"
#read -n 1 -s -r -p " Press any key to back on menu"
#menu
exit 0
