#!/bin/bash
exit_clean() { echo " Dihentikan"; exit 0; }
trap exit_clean SIGINT
engkok=$0
REPOKU="https://www.vmessh.cloud"
REPOSC="https://iam.scvpn.cloud"
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/alawivpn/theme/color.conf)
N='\e[0m'
R='\e[1;91m'
G='\e[1;92m'
Y='\e[1;93m'
W='\e[1;97m'
U="$(cat /etc/alawivpn/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
O="$(cat /etc/alawivpn/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
ipsaya=$(wget -qO- ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="${REPOKU}/registrasi.txt"

# FUNCTIONKU
garis(){ echo -e " $U$*$N"; }
judul(){ echo -e " $O$*$N"; }
tebal(){ echo -e " $W$*$N"; }
tulis(){ echo -e " $N$*$N"; }
checking_sc() {
    useexp=$(curl -sS "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ "$date_list" > "$useexp" ]]; then
        systemctl stop nginx
        systemctl stop kyt
        systemctl stop xray
        systemctl stop ws-stunnel
        dilarang
        exit 1
    else
        echo -ne
    fi
}
checking_sc

# MENU HABIS REBOOT/BOOTING
clear
echo
garis "═══════════════════════════════════════════"
judul "        ◈ MENU UTAMA SAAT BOOTING ◈        "
garis "═══════════════════════════════════════════"
echo
tulis "${G}◈${W} Ketik ${G}menu${W} untuk menampilkan menu"
tulis "${G}◈${W} Ketik ${G}reset${W} untuk merestart service"
tulis "${G}◈${W} Ketik ${G}a${W} untuk membersihkan latar belakang"
tulis "${G}◈${W} Ketik ${G}x${W} untuk keluar"
echo
garis "═══════════════════════════════════════════"
echo
exit 0
